/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

import org.LabExecutor.Algoritms.DoublePass.BlockHuffman;

class AppTest {

  @Test
  void adaptHuffmanTest() {
    
  }
}
